# demande de certificat pour notre domaine 'ndl.super-sympa.fr'
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ndl-certificate
  namespace: ndl
spec:
  # certificats
  dnsNames:
  - 'ndl.super-sympa.fr'

  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-super-sympa-issuer #notre issuer
  # Secret pour stocker les certificats
  secretName: ndl-secret-certificate
