# gestion des certificats automatique avec letencrypt !
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: cert-manager-super-sympa-issuer
 namespace: ndl
spec:
 acme:
   email: corentin.at@tutanota.com
   server: https://acme-v02.api.letsencrypt.org/directory # production
   privateKeySecretRef:
     name: cert-manager-super-sympa-private-key # certificat
   solvers:
   - http01:
        ingress:
          class: traefik
